name: Generate Snake Game

# grant write access to repository contents
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # ensure the checkout action uses GITHUB_TOKEN with write perms
        with:
          persist-credentials: true
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github&color_snake=#1c1c84
            output/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#1c1c84
            output/github-contribution-grid-snake.gif?color_snake=#1c1c84
      - name: Commit & push snake animation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "ci: update snake game animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
