name: Generate Snake Game

# Run weekly (Sunday UTC midnight) and also allow manual triggers
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-snake:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your profile repo
      - uses: actions/checkout@v3

      # 2. Generate the snake animation (SVG + dark-mode SVG + GIF)
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github
            output/github-contribution-grid-snake-dark.svg?palette=github-light
            output/github-contribution-grid-snake.gif?color_snake=#1c1c84

      # 3. Commit and push the generated files back to your repo
      - name: Commit and push snake animation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "ci: update snake game animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
